BASE:
  #log等级
  log_level: "debug"
  #扩展名
  log_extension: ".log"
  test:
    url: ""
    case_file: "testdata.xlsx"
    case_sheet: "九宫格抽奖系统"


email:
  smtpserver: "smtp.qq.com"
  username: "903255458@qq.com"
  password: "FDSArewq1"
  receiver: "903255458@qq.com"
